[package]
name = "oreb"
authors = ["Nathan Clack"]
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
log = "0.4"
thiserror = "1.0"
wgpu = "0.16"
winit = "0.28"

[dev-dependencies]
dotenv = "0.15"
env_logger = "0.10"
async-std = { version = "1.12.0", features = ["attributes"] }
